id: content_admin
permissions:
  - 'customize shortcut links'
  - 'access toolbar'
  - 'access admin audit trail'
  - 'administer footer menu items'
  - 'administer main menu items'
  - 'access coffee'
  - 'access responsive preview'
