id: site_admin
permissions:
  - 'administer shortcuts'
  - 'customize shortcut links'
  - 'switch shortcut sets'
  - 'access toolbar'
  - 'delete_homepage_node'
  - 'access admin audit trail'
  - 'administer admin menu items'
  - 'administer footer menu items'
  - 'administer main menu items'
  - 'administer tools menu items'
  - 'administer account menu items'
  - 'access coffee'
  - 'masquerade as authenticated'
  - 'masquerade as content_admin'
  - 'masquerade as editor'
  - 'masquerade as seo_admin'
  - 'masquerade as site_admin'
  - 'assign roles'
  - 'userprotect.protected_site_admin.bypass'
  - 'access responsive preview'
