id: site_admin
permissions:
  - 'access contextual links'
  - 'create url aliases'
  - 'access taxonomy overview'
  - 'administer taxonomy'
  - 'break content lock'
  - 'manipulate all entityqueues'
  - 'manipulate entityqueues'
  - 'administer block classes'
  - 'access varbase settings'
