name: Varbase Security - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
config:
  actions:
    user.role.site_admin:
      grantPermissions:
        - 'administer flood unblock'
        - 'flood unblock ips'
