<?php

/**
 * @file
 * Contains varbase_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\Yaml\Yaml;
use Vardot\Entity\EntityDefinitionUpdateManager;

// To have all varbase core general and global tokens.
\Drupal::moduleHandler()->loadInclude('varbase_core', 'inc', 'varbase_core.tokens');

/**
 * Implements hook_FORM_ID_form_alter().
 */
function varbase_core_form_node_form_alter(&$form, FormStateInterface $form_state) {
  // Override node form sidebar order.
  if (isset($form['author'])) {
    $form['author']['#weight'] = -6;
  }
  if (isset($form['field_comments'])) {
    $form['field_comments']['widget'][0]['#weight'] = -5;
  }
  if (isset($form['path_settings'])) {
    $form['path_settings']['#weight'] = -4;
  }
  if (isset($form['field_meta_tags'])) {
    $form['field_meta_tags']['widget'][0]['#weight'] = -3;
  }
  if (isset($form['simple_sitemap'])) {
    $form['simple_sitemap']['#weight'] = -2;
  }
  if (isset($form['ds_switch_view_mode'])) {
    $form['ds_switch_view_mode']['#weight'] = 101;
  }
}

/**
 * Implements hook_form_alter().
 */
function varbase_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Disable the checkbox to delete referenced entity from entityqueues.
  $subqueue_base_form = $form_state->getBuildInfo();
  if (array_key_exists('base_form_id', $subqueue_base_form)
    && $subqueue_base_form['base_form_id'] == 'entity_subqueue_form'
    && isset($form['items']['widget']['entities'])
    && !empty($form['items']['widget']['entities'])) {

    foreach ($form['items']['widget']['entities'] as &$subqueue_entity) {
      if (is_array($subqueue_entity)) {
        if (array_key_exists('form', $subqueue_entity) && array_key_exists('delete', $subqueue_entity['form'])) {
          $subqueue_entity['form']['delete']['#access'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function varbase_core_template_preprocess_default_variables_alter(&$variables) {
  $user_settings_config = \Drupal::config('user.settings');
  $variables['user_settings_register_admin_only'] = $user_settings_config->get('register') == 'admin_only' ? 1 : 0;
}

/**
 * Implements hook_modules_installed().
 */
function varbase_core_modules_installed($modules, $is_syncing) {
  if (in_array('automated_cron', $modules)) {

    $managed_config_module_path = 'automated_cron';
    $managed_config_path = Drupal::service('module_handler')->getModule('varbase_core')->getPath() . '/config/managed/' . $managed_configs_module_path;

    // Import managed configs to the site active configs.
    $config_name = 'automated_cron.settings';
    $config_path = $managed_config_path . '/' . $config_name . '.yml';
    $config_content = file_get_contents($config_path);
    $config_data = (array) Yaml::parse($config_content);
    $config_factory = \Drupal::configFactory()->getEditable($config_name);
    $config_factory->setData($config_data)->save(TRUE);

    // Entity updates to clear up any mismatched entity and/or field definitions
    // And Fix changes were detected in the entity type and field definitions.
    \Drupal::classResolver()
      ->getInstanceFromDefinition(EntityDefinitionUpdateManager::class)
      ->applyUpdates();
  }
}
