<?php

/**
 * @file
 * Install, update and uninstall functions for the Varbase core module.
 */

use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;
use Vardot\Entity\EntityDefinitionUpdateManager;
use Vardot\Installer\ModuleInstallerFactory;

// Include all helpers and updates.
include_once __DIR__ . '/includes/helpers.inc';
include_once __DIR__ . '/includes/updates.inc';

/**
 * Implements hook_install().
 */
function varbase_core_install() {

  // Processor for install: in varbase_core.info.yml file.
  // --------------------------------------------------------------------------.
  ModuleInstallerFactory::installList('varbase_core');

  // Install optional configs.
  ModuleInstallerFactory::importConfigsFromScanedDirectory('varbase_core', '/^field.storage.*\\.(yml)$/i');
  ModuleInstallerFactory::importConfigsFromScanedDirectory('varbase_core', '/^.*(settings.yml)$/i');

  // --------------------------------------------------------------------------.
  // Entity updates to clear up any mismatched entity and/or field definitions
  // And Fix changes were detected in the entity type and field definitions.
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EntityDefinitionUpdateManager::class)
    ->applyUpdates();

  // Grant role permissions via the default recipe.
  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  RecipeRunner::processRecipe($default_recipe);
}
