id: site_admin
permissions:
  - 'access webform overview'
  - 'create webform'
  - 'delete any webform submission'
  - 'edit webform assets'
  - 'edit any webform'
  - 'view any webform submission'
  - 'clone webform entity'
