name: Varbase Tour - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - tour
config:
  strict: false
  import:
    tour: '*'
    varbase_tour:
      - tour.tour.welcome_to_varbase
  actions:
    user.role.authenticated:
      grantPermissions:
        - 'access tour'
    tour.settings:
      simpleConfigUpdate:
        hide_tour_when_empty: true
        display_custom_labels: false
        tour_avail_text: ''
        tour_no_avail_text: ''
