varbase_security.password_confirmation_suggestions.settings:
  type: config_object
  label: 'Varbase Security Password Confirmation suggestions message settings'
  mapping:
    confirmTitle:
      type: label
      label: 'Confirm Title'
    confirmSuccess:
      type: label
      label: 'Confirm Success'
    confirmFailure:
      type: label
      label: 'Confirm Failure'
    strengthTitle:
      type: label
      label: 'Strength Title'
    hasWeaknesses:
      type: label
      label: 'Recommendation Statement'
    tooShort:
      type: label
      label: 'Too Short Title'
    addLowerCase:
      type: label
      label: 'Lowercase Title'
    addUpperCase:
      type: label
      label: 'Uppercase Title'
    addNumbers:
      type: label
      label: 'Numbers Title'
    addPunctuation:
      type: label
      label: 'Punctuation Title'
    sameAsUsername:
      type: label
      label: 'If same as username'
    weak:
      type: label
      label: 'Weak'
    fair:
      type: label
      label: 'Fair'
    good:
      type: label
      label: 'Good'
    strong:
      type: label
      label: 'Strong'
