name: Varbase Admin - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - admin_audit_trail
  - admin_audit_trail_file
  - admin_audit_trail_media
  - admin_audit_trail_user
  - admin_audit_trail_taxonomy
  - admin_audit_trail_node
  - admin_audit_trail_menu
  - admin_audit_trail_auth
  - masquerade
  - menu_admin_per_menu
  - responsive_preview
  - revision_log_default
  - syslog
  - update
  - settings_tray
  - entity_clone
  - taxonomy_manager
  - taxonomy_access_fix
  - coffee
  - length_indicator
  - admin_toolbar
  - admin_toolbar_tools
  - gin_toolbar
  - gin_login
  - gin_moderation_sidebar
  - gin_everywhere
config:
  actions:
    user.settings:
      simple_config_update:
        register: admin_only
    node.settings:
      simple_config_update:
        use_admin_theme: true
    gin.settings:
      simple_config_update:
        logo:
          path: profiles/contrib/varbase/images/varbase-medium-logo-emblem-color.png
          use_default: false
        favicon:
          mimetype: image/vnd.microsoft.icon
          path: profiles/contrib/varbase/images/favicon.ico
          use_default: false
    gin_login.settings:
      simple_config_update:
        logo:
          use_default: false
          path: themes/contrib/vartheme_bs5/logo.svg
        brand_image:
          use_default: true
    roleassign_roles:
      simple_config_update:
        editor: editor
        content_admin: content_admin
        site_admin: site_admin
        administrator: "0"
    config_perms.custom_perms_entity.administer_account_settings:
      simple_config_update:
        label: "Administer account settings"
        route: entity.user.admin_form
    config_perms.custom_perms_entity.administer_date_time:
      simple_config_update:
        label: "Administer date-time"
        route: entity.date_format.collection
    config_perms.custom_perms_entity.administer_error_logs:
      simple_config_update:
        label: "Administer error logs"
        route: dblog.overview
    config_perms.custom_perms_entity.administer_file_system:
      simple_config_update:
        label: "Administer file system"
        route: system.file_system_settings
    user.role.authenticated:
      grantPermissions:
        - 'access shortcuts'
        - 'userprotect.account.edit'
        - 'userprotect.mail.edit'
        - 'userprotect.pass.edit'
    user.role.editor:
      grantPermissions:
        - 'customize shortcut links'
        - 'access toolbar'
        - 'access admin audit trail'
        - 'access coffee'
        - 'access responsive preview'
        - 'clone node entity'
        - 'access taxonomy manager list'
    user.role.seo_admin:
      grantPermissions:
        - 'customize shortcut links'
        - 'access toolbar'
        - 'access admin audit trail'
        - 'access coffee'
        - 'access responsive preview'
    user.role.content_admin:
      grantPermissions:
        - 'customize shortcut links'
        - 'access toolbar'
        - 'access admin audit trail'
        - 'administer footer menu items'
        - 'administer main menu items'
        - 'access coffee'
        - 'access responsive preview'
        - 'clone block entity'
        - 'clone block_content entity'
        - 'clone node entity'
        - 'clone menu_link_content entity'
        - 'clone user entity'
        - 'clone taxonomy_term entity'
        - 'clone taxonomy_vocabulary entity'
        - 'access taxonomy manager list'
    user.role.site_admin:
      grantPermissions:
        - 'administer shortcuts'
        - 'customize shortcut links'
        - 'switch shortcut sets'
        - 'access toolbar'
        - 'delete_homepage_node'
        - 'access admin audit trail'
        - 'administer admin menu items'
        - 'administer footer menu items'
        - 'administer main menu items'
        - 'administer tools menu items'
        - 'administer account menu items'
        - 'access coffee'
        - 'masquerade as authenticated'
        - 'masquerade as content_admin'
        - 'masquerade as editor'
        - 'masquerade as seo_admin'
        - 'masquerade as site_admin'
        - 'assign roles'
        - 'userprotect.protected_site_admin.bypass'
        - 'access responsive preview'
        - 'clone block entity'
        - 'clone block_content entity'
        - 'clone node entity'
        - 'clone menu_link_content entity'
        - 'clone user entity'
        - 'clone taxonomy_term entity'
        - 'clone taxonomy_vocabulary entity'
        - 'access taxonomy manager list'