name: varbase_admin_update_100003
description: 'Issue #3426347: Add Taxonomy Manager ~2 module to Varbase Admin As part of enhancing Editorial UX for taxonomy and term management.'
type: update
install:
  - taxonomy_manager
config:
  actions:
    user.role.site_admin:
      grantPermissions:
        - 'access taxonomy manager list'
    user.role.content_admin:
      grantPermissions:
        - 'access taxonomy manager list'
    user.role.editor:
      grantPermissions:
        - 'access taxonomy manager list'
