__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_admin
__global_actions:
  expected_config: {}
  update_actions: {}
  install_modules:
    - length_indicator
