__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_media
__global_actions:
  expected_config: {}
  update_actions: {}
  import_configs:
    - varbase_media.settings
    - image.style.blazy_blurry
