__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_seo
__global_actions:
  expected_config: {}
  update_actions: {}
  install_modules:
    - script_manager
