__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_core
__global_actions:
  expected_config: {}
  update_actions: {}
  install_modules:
    - email_registration
  import_configs:
    - core.entity_form_display.user.user.register
email_registration.settings:
  expected_config:
    login_with_username: false
  update_actions:
    change:
      login_with_username: true
core.entity_form_display.user.user.default:
  expected_config:
    content:
      user_picture:
        weight: -1
  update_actions:
    content:
      user_picture:
        weight: 30
