__global_conditions:
  expected_config: {}
  update_actions: {}
  expected_modules:
    - varbase_core
__global_actions:
  expected_config: {}
  update_actions: {}
  install_modules:
    - email_registration
  import_configs:
    - email_registration.settings
    - core.entity_form_display.user.user.register
core.entity_form_display.user.user.default:
  expected_config:
    content:
      account:
        weight: -10
        region: content
      contact:
        weight: 5
        region: content
      language:
        weight: 0
        region: content
      timezone:
        weight: 6
        region: content
      user_picture:
        type: image_image
        settings:
          progress_indicator: throbber
          preview_image_style: thumbnail
        third_party_settings: {}
        weight: -1
        region: content
  update_actions:
    content:
      account:
        weight: 0
        region: content
        settings: {  }
        third_party_settings: {  }
      contact:
        weight: 5
        region: content
      google_analytics:
        weight: 3
        region: content
        settings: {  }
        third_party_settings: {  }
      language:
        weight: 1
        region: content
        settings: {  }
        third_party_settings: {  }
      path:
        type: path
        weight: 30
        region: content
        settings: {  }
        third_party_settings: {  }
      timezone:
        weight: 2
        region: content
        settings: {  }
        third_party_settings: {  }
      user_picture:
        type: image_image
        weight: 3
        region: content
        settings:
          progress_indicator: throbber
          preview_image_style: thumbnail
        third_party_settings: {  }